mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: 51.195.235.71
  port: 2052
  uuid: 59e28f78-c31b-4613-9d9f-1e6732a31f46
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.195.235.71
  client-fingerprint: ''
- name: 'ARISTA #2'
  type: vmess
  server: 212.87.198.79
  port: 45255
  uuid: dd5ffd23-cef5-44dd-a143-658bd7f3943a
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bale.ai
  client-fingerprint: ''
- name: 'ARISTA #3'
  type: vmess
  server: 134.195.196.211
  port: 18000
  uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 134.195.196.211
  client-fingerprint: ''
- name: 'ARISTA #4'
  type: vmess
  server: 212.87.198.79
  port: 45255
  uuid: dd5ffd23-cef5-44dd-a143-658bd7f3943a
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bale.ai
  client-fingerprint: ''
- name: 'ARISTA #5'
  type: vmess
  server: uk.connfull.org
  port: 2053
  uuid: d64d52b1-144f-4bce-a6d7-1324de187b1b
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: uk.connfull.org
  client-fingerprint: ''
  alpn:
  - http/1.1
- name: 'ARISTA #6'
  type: vmess
  server: 172.104.80.66
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 172.104.80.66
  client-fingerprint: ''
- name: 'ARISTA #7'
  type: vmess
  server: 212.87.198.79
  port: 45255
  uuid: dd5ffd23-cef5-44dd-a143-658bd7f3943a
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bale.ai
  client-fingerprint: ''
- name: 'ARISTA #8'
  type: vmess
  server: client.game2dns.xyz
  port: 3187
  uuid: c2a301a2-64d4-470f-86ca-ddea14bdf951
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: client.game2dns.xyz
  client-fingerprint: ''
- name: 'ARISTA #9'
  type: vmess
  server: 38.107.236.159
  port: 49023
  uuid: 3236d336-c042-4ef5-9740-d7cd5b9af5ce
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 38.107.236.159
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: 38.107.236.159
- name: 'ARISTA #10'
  type: vmess
  server: 209.250.245.206
  port: 35007
  uuid: 25c54771-12fd-4b37-a969-9e0391274cca
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 209.250.245.206
  client-fingerprint: ''
- name: 'ARISTA #11'
  type: vmess
  server: 51.83.197.140
  port: 80
  uuid: 7d8c2904-0917-4002-bff9-9a44e1c92fb1
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.83.197.140
  client-fingerprint: ''
  ws-opts:
    path: /api/v1
    headers:
      Host: 51.83.197.140
- name: 'ARISTA #12'
  type: vmess
  server: 172.233.17.76
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 172.233.17.76
  client-fingerprint: ''
- name: 'ARISTA #13'
  type: vmess
  server: 45.92.70.236
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 45.92.70.236
  client-fingerprint: ''
- name: 'ARISTA #14'
  type: vmess
  server: 51.195.235.71
  port: 2052
  uuid: 59e28f78-c31b-4613-9d9f-1e6732a31f46
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.195.235.71
  client-fingerprint: ''
- name: 'ARISTA #15'
  type: vmess
  server: s2.projectv.bond
  port: 42444
  uuid: 8521095b-5512-4589-9688-18750f3aa6b4
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: s2.projectv.bond
  client-fingerprint: ''
- name: 'ARISTA #16'
  type: vmess
  server: 209.250.245.206
  port: 35007
  uuid: c44510cf-e271-401b-8a52-6010ab7609dd
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 209.250.245.206
  client-fingerprint: ''
- name: 'ARISTA #17'
  type: vmess
  server: 95.179.140.164
  port: 16784
  uuid: c304c72f-54cc-4e9c-859e-ff36d9515143
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 95.179.140.164
  client-fingerprint: ''
- name: 'ARISTA #18'
  type: vmess
  server: 209.250.245.206
  port: 35007
  uuid: 25c54771-12fd-4b37-a969-9e0391274cca
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 209.250.245.206
  client-fingerprint: ''
- name: 'ARISTA #19'
  type: vmess
  server: 103.31.79.186
  port: 443
  uuid: 2f3aadae-66c6-4dca-a670-03c183f8024e
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sctest1.dr-ping.ir
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
  ws-opts:
    path: /kos-nanat-decoder
    headers:
      Host: sctest1.dr-ping.ir
- name: 'ARISTA #20'
  type: vmess
  server: 134.195.196.211
  port: 18000
  uuid: f8c8dc3d-0d37-46b0-8b34-a7232882fcfe
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 134.195.196.211
  client-fingerprint: ''
- name: 'ARISTA #21'
  type: vmess
  server: 51.83.197.140
  port: 80
  uuid: 7d8c2904-0917-4002-bff9-9a44e1c92fb1
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.83.197.140
  client-fingerprint: ''
  ws-opts:
    path: /api/v1
    headers:
      Host: 51.83.197.140
- name: 'ARISTA #22'
  type: vmess
  server: 212.87.198.79
  port: 45255
  uuid: dd5ffd23-cef5-44dd-a143-658bd7f3943a
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bale.ai
  client-fingerprint: ''
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
