mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: node-de.connectsuite.org
  port: 2053
  uuid: fd169a0a-5c32-4f3e-9b6c-28dd35f2a5e5
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: node-de.connectsuite.org
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #2'
  type: vmess
  server: de5.taskflowhub.org
  port: 2053
  uuid: ca58b165-0f7d-49aa-9fae-a017e8a0f884
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: de5.taskflowhub.org
  client-fingerprint: ''
- name: 'ARISTA #3'
  type: vmess
  server: node-fr.connectsuite.org
  port: 2053
  uuid: 2f4234f9-8f33-4c7f-952f-565ffa5f5fb7
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: node-fr.connectsuite.org
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #4'
  type: vmess
  server: 188.114.97.21
  port: 443
  uuid: f584de15-2034-4170-a723-f48c2bae5e0f
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: afrhms16v.bestxray.buzz
  client-fingerprint: chrome
  ws-opts:
    path: /linkws
    headers:
      Host: afrhms16v.bestxray.buzz
- name: 'ARISTA #5'
  type: vmess
  server: 104.19.45.84
  port: 2095
  uuid: 7a737f41-b792-4260-94ff-3d864da67b80
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: onea.flha.ru
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: onea.flha.ru
- name: 'ARISTA #6'
  type: vmess
  server: www.arvancloud.ir
  port: 8880
  uuid: c534085e-0c5c-4e31-b3b8-b0ddde551a83
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bamangadambezan.speedtest2026.ir
  client-fingerprint: ''
  ws-opts:
    path: /hugme
    headers:
      Host: bamangadambezan.speedtest2026.ir
- name: 'ARISTA #7'
  type: vmess
  server: 139.162.152.81
  port: 25241
  uuid: a55b3190-5901-4e4e-ac4b-b7878bc225b7
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 139.162.152.81
  client-fingerprint: ''
- name: 'ARISTA #8'
  type: vmess
  server: 51.195.235.71
  port: 2052
  uuid: 59e28f78-c31b-4613-9d9f-1e6732a31f46
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.195.235.71
  client-fingerprint: ''
- name: 'ARISTA #9'
  type: vmess
  server: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  port: 21805
  uuid: 56957d32-56b5-45d6-995f-e7296db82c99
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: b51d64cb-c5d6-4791-8ecf-0a6d8d71c717.wtf
  client-fingerprint: ''
- name: 'ARISTA #10'
  type: vmess
  server: de4.niekotin.de
  port: 80
  uuid: 38ed5d70-443e-4ac3-b877-ea21d97fed93
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: de4.niekotin.de
  client-fingerprint: ''
  ws-opts:
    path: /vmess
    headers:
      Host: de4.niekotin.de
- name: 'ARISTA #11'
  type: vmess
  server: uuipo.ice.lol
  port: 46474
  uuid: 51919eb8-46d1-4daf-a705-35ae2415d8f1
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: uuipo.ice.lol
  client-fingerprint: ''
- name: 'ARISTA #12'
  type: vmess
  server: uuipo.ice.lol
  port: 46474
  uuid: 51919eb8-46d1-4daf-a705-35ae2415d8f1
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: uuipo.ice.lol
  client-fingerprint: ''
- name: 'ARISTA #13'
  type: vmess
  server: 104.26.5.67
  port: 2086
  uuid: e9e3cc13-db48-4cc1-8c24-7626439a5339
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ip1.1789034.xyz
  client-fingerprint: chrome
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: ip1.1789034.xyz
- name: 'ARISTA #14'
  type: vmess
  server: 188.114.97.7
  port: 443
  uuid: edbb1059-1633-4271-b66e-ed4fba47a1bf
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: linde06.indiavideo.sbs
  client-fingerprint: ''
  ws-opts:
    path: /linkws
    headers:
      Host: linde06.indiavideo.sbs
- name: 'ARISTA #15'
  type: vmess
  server: 4.hk.zz.xxxxx.x-t-fuckword.network
  port: 36676
  uuid: 244effd9-0204-3c4a-8537-0dca4e5fd9b5
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 4.hk.zz.xxxxx.x-t-fuckword.network
  client-fingerprint: chrome
- name: 'ARISTA #16'
  type: vmess
  server: 172.64.198.249
  port: 2086
  uuid: e9e3cc13-db48-4cc1-8c24-7626439a5339
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ip1.1457230.xyz
  client-fingerprint: chrome
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: ip1.1457230.xyz
- name: 'ARISTA #17'
  type: vmess
  server: c12s4.jamjams3.net
  port: 12623
  uuid: 8ff878d1-eaf8-4afd-8cbb-6d657596af64
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: c12s4.jamjams3.net
  client-fingerprint: chrome
- name: 'ARISTA #18'
  type: vmess
  server: 104.19.45.50
  port: 2086
  uuid: e9e3cc13-db48-4cc1-8c24-7626439a5339
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ip13.freegradely.xyz
  client-fingerprint: ''
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: ip13.freegradely.xyz
- name: 'ARISTA #19'
  type: vmess
  server: 51.195.235.71
  port: 2052
  uuid: 59e28f78-c31b-4613-9d9f-1e6732a31f46
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.195.235.71
  client-fingerprint: ''
- name: 'ARISTA #20'
  type: vmess
  server: de5.taskflowhub.org
  port: 2053
  uuid: ca58b165-0f7d-49aa-9fae-a017e8a0f884
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: de5.taskflowhub.org
  client-fingerprint: ''
- name: 'ARISTA #21'
  type: vmess
  server: 95.179.187.188
  port: 57220
  uuid: 13a400f3-e4d6-4cc6-840e-8cc9c52e9c25
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 95.179.187.188
  client-fingerprint: ''
- name: 'ARISTA #22'
  type: vmess
  server: snapp.ir
  port: 8080
  uuid: b63d4c13-dd84-44b4-b901-28f9f383cecb
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: javad.trmas-ps.ir
  client-fingerprint: ''
  ws-opts:
    path: /
    headers:
      Host: javad.trmas-ps.ir
- name: 'ARISTA #23'
  type: vmess
  server: 51.195.235.71
  port: 2052
  uuid: 59e28f78-c31b-4613-9d9f-1e6732a31f46
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.195.235.71
  client-fingerprint: ''
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
