mixed-port: 7890
ipv6: false
allow-lan: true
mode: rule
log-level: warning
unified-delay: false
tcp-concurrent: true
geo-auto-update: true
geo-update-interval: 168
external-controller: 127.0.0.1:9090
external-controller-cors:
  allow-origins:
  - '*'
  allow-private-network: true
external-ui: ui
external-ui-url: https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip
profile:
  store-selected: true
  store-fake-ip: true
dns:
  enable: true
  respect-rules: true
  use-system-hosts: false
  listen: 0.0.0.0:1053
  ipv6: false
  nameserver:
  - 8.8.8.8
  - 1.1.1.1
  proxy-server-nameserver:
  - 8.8.8.8
  direct-nameserver:
  - 8.8.8.8
  direct-nameserver-follow-policy: true
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
  - '*.lan'
  - '*.local'
  - '*.localhost'
  - '*.ir'
  - '*.test'
  - '*.localdomain'
  - '*.home'
  - '*.internal'
tun:
  enable: true
  stack: gvisor
  auto-route: true
  strict-route: true
  auto-detect-interface: true
  dns-hijack:
  - any:53
  - tcp://any:53
  mtu: 9000
sniffer:
  enable: true
  force-dns-mapping: true
  parse-pure-ip: true
  override-destination: true
  sniff:
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
    TLS:
      ports:
      - 443
      - 8443
      - 2053
      - 2083
      - 2087
      - 2096
proxies:
- name: 'ARISTA #1'
  type: vmess
  server: 4.hk.zz.xxxxx.x-t-fuckword.network
  port: 36676
  uuid: 244effd9-0204-3c4a-8537-0dca4e5fd9b5
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 4.hk.zz.xxxxx.x-t-fuckword.network
  client-fingerprint: chrome
- name: 'ARISTA #2'
  type: vmess
  server: 172.64.198.249
  port: 2086
  uuid: e9e3cc13-db48-4cc1-8c24-7626439a5339
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: ip1.1457230.xyz
  client-fingerprint: chrome
  ws-opts:
    path: github.com/Alvin9999
    headers:
      Host: ip1.1457230.xyz
- name: 'ARISTA #3'
  type: vmess
  server: 104.19.45.84
  port: 2095
  uuid: 7a737f41-b792-4260-94ff-3d864da67b80
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: onea.flha.ru
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: onea.flha.ru
- name: 'ARISTA #4'
  type: vmess
  server: 188.114.97.21
  port: 443
  uuid: f584de15-2034-4170-a723-f48c2bae5e0f
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: afrhms16v.bestxray.buzz
  client-fingerprint: chrome
  ws-opts:
    path: /linkws
    headers:
      Host: afrhms16v.bestxray.buzz
- name: 'ARISTA #5'
  type: vmess
  server: c12s4.jamjams3.net
  port: 12623
  uuid: 8ff878d1-eaf8-4afd-8cbb-6d657596af64
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: c12s4.jamjams3.net
  client-fingerprint: chrome
- name: 'ARISTA #6'
  type: vmess
  server: 87.107.162.243
  port: 25105
  uuid: 8769d5d8-d611-47bb-9d20-2980a47c2b02
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 87.107.162.243
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: 87.107.162.243
- name: 'ARISTA #7'
  type: vmess
  server: 172.233.17.76
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 172.233.17.76
  client-fingerprint: ''
- name: 'ARISTA #8'
  type: vmess
  server: www.arvancloud.ir
  port: 8880
  uuid: c534085e-0c5c-4e31-b3b8-b0ddde551a83
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: bamangadambezan.speedtest2026.ir
  client-fingerprint: ''
  ws-opts:
    path: /hugme
    headers:
      Host: bamangadambezan.speedtest2026.ir
- name: 'ARISTA #9'
  type: vmess
  server: spt.reata.ir
  port: 1050
  uuid: b5b183b6-a4f0-41ad-a015-ba9f000ad7ed
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: spt.reata.ir
  client-fingerprint: ''
- name: 'ARISTA #10'
  type: vmess
  server: node-de.connectsuite.org
  port: 2053
  uuid: fd169a0a-5c32-4f3e-9b6c-28dd35f2a5e5
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: node-de.connectsuite.org
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #11'
  type: vmess
  server: de5.taskflowhub.org
  port: 2053
  uuid: ca58b165-0f7d-49aa-9fae-a017e8a0f884
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: de5.taskflowhub.org
  client-fingerprint: ''
- name: 'ARISTA #12'
  type: vmess
  server: 172.232.103.186
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 172.232.103.186
  client-fingerprint: ''
- name: 'ARISTA #13'
  type: vmess
  server: jp.mousse.tk
  port: 16650
  uuid: d66a47f2-5136-492c-c82a-74835bb03a76
  alterId: 0
  cipher: auto
  network: ''
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: jp.mousse.tk
  client-fingerprint: chrome
- name: 'ARISTA #14'
  type: vmess
  server: 192.74.243.45
  port: 49206
  uuid: 418048af-a293-4b99-9b0c-98ca3580dd24
  alterId: 64
  cipher: auto
  network: ''
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 192.74.243.45
  client-fingerprint: chrome
- name: 'ARISTA #15'
  type: vmess
  server: sg.multiport1.artunnel57.host
  port: 443
  uuid: c498fa2e-e4c3-4fe8-a2c6-110c88806a70
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: sg.multiport1.artunnel57.host
  client-fingerprint: chrome
  ws-opts:
    path: /vmess-tls
    headers:
      Host: sg.multiport1.artunnel57.host
- name: 'ARISTA #16'
  type: vmess
  server: 45.85.118.88
  port: 443
  uuid: ee30d3ff-da14-4ea8-bcd2-02e8ee3667de
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: hstr1675520106270.aidapp.life
  client-fingerprint: chrome
  ws-opts:
    path: /aidapp.lifevws
    headers:
      Host: hstr1675520106270.aidapp.life
- name: 'ARISTA #17'
  type: vmess
  server: 5.75.139.201
  port: 80
  uuid: 5e334049-1973-4bb6-82b0-3ec33e25aae2
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 5.75.139.201
  client-fingerprint: chrome
  ws-opts:
    path: /graphql
    headers:
      Host: 5.75.139.201
- name: 'ARISTA #18'
  type: vmess
  server: i.toxicfa.cf
  port: 8880
  uuid: 75aae5be-0838-4ada-fdf1-1d0ea41fca55
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: i.toxicfa.cf
  client-fingerprint: chrome
  ws-opts:
    path: /
    headers:
      Host: i.toxicfa.cf
- name: 'ARISTA #19'
  type: vmess
  server: 216.106.183.35
  port: 22324
  uuid: 04621bae-ab36-11ec-b909-0242ac120002
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 216.106.183.35
  client-fingerprint: chrome
- name: 'ARISTA #20'
  type: vmess
  server: node-fr.connectsuite.org
  port: 2053
  uuid: 2f4234f9-8f33-4c7f-952f-565ffa5f5fb7
  alterId: 0
  cipher: auto
  network: tcp
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: node-fr.connectsuite.org
  client-fingerprint: chrome
  alpn:
  - h2
  - http/1.1
- name: 'ARISTA #21'
  type: vmess
  server: cf.scpnb.top
  port: 443
  uuid: 7fd8d1db-96ec-4e46-80a8-74ad9472384e
  alterId: 0
  cipher: auto
  network: ws
  tls: true
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: graph-keep-beds-catalog.trycloudflare.com
  client-fingerprint: ''
  ws-opts:
    path: /7fd8d1db-96ec-4e46-80a8-74ad9472384e-vm
    headers:
      Host: graph-keep-beds-catalog.trycloudflare.com
- name: 'ARISTA #22'
  type: vmess
  server: 47.250.45.234
  port: 8613
  uuid: 80039b4d-bac0-4f89-82c7-54fad3b0a1ea
  alterId: 0
  cipher: auto
  network: ws
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 47.250.45.234
  client-fingerprint: ''
  ws-opts:
    path: /arki?ed=2048
    headers:
      Host: 47.250.45.234
- name: 'ARISTA #23'
  type: vmess
  server: 51.195.235.71
  port: 2052
  uuid: 59e28f78-c31b-4613-9d9f-1e6732a31f46
  alterId: 0
  cipher: auto
  network: tcp
  tls: false
  udp: true
  skip-cert-verify: false
  tcp-fast-open: true
  servername: 51.195.235.71
  client-fingerprint: ''
proxy-groups:
- name: Proxy Select
  type: select
  proxies:
  - Auto Select
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  - DIRECT
- name: Auto Select
  type: url-test
  proxies:
  - 'ARISTA #1'
  - 'ARISTA #2'
  - 'ARISTA #3'
  - 'ARISTA #4'
  - 'ARISTA #5'
  - 'ARISTA #6'
  - 'ARISTA #7'
  - 'ARISTA #8'
  - 'ARISTA #9'
  - 'ARISTA #10'
  - 'ARISTA #11'
  - 'ARISTA #12'
  - 'ARISTA #13'
  - 'ARISTA #14'
  - 'ARISTA #15'
  - 'ARISTA #16'
  - 'ARISTA #17'
  - 'ARISTA #18'
  - 'ARISTA #19'
  - 'ARISTA #20'
  - 'ARISTA #21'
  - 'ARISTA #22'
  - 'ARISTA #23'
  url: http://www.gstatic.com/generate_204
  interval: 300
  tolerance: 150
  lazy: true
rules:
- DOMAIN-SUFFIX,net2025.afsharidempire.uk,DIRECT
- DOMAIN,cp.cloudflare.com,Auto Select
- DOMAIN-SUFFIX,cdn.ir,DIRECT
- DOMAIN-SUFFIX,aparat.com,DIRECT
- DOMAIN-SUFFIX,digikala.com,DIRECT
- DOMAIN-SUFFIX,divar.ir,DIRECT
- DOMAIN-SUFFIX,snapp.ir,DIRECT
- DOMAIN-SUFFIX,torob.com,DIRECT
- DOMAIN-SUFFIX,bamilo.com,DIRECT
- DOMAIN-SUFFIX,alibaba.ir,DIRECT
- DOMAIN-SUFFIX,ban.ir,DIRECT
- DOMAIN-KEYWORD,telegram,Auto Select
- DOMAIN-SUFFIX,t.me,Auto Select
- DOMAIN-SUFFIX,telegram.org,Auto Select
- DOMAIN-SUFFIX,google.com,Auto Select
- DOMAIN-SUFFIX,youtube.com,Auto Select
- DOMAIN-SUFFIX,github.com,Auto Select
- DOMAIN-SUFFIX,instagram.com,Auto Select
- DOMAIN-SUFFIX,twitter.com,Auto Select
- DOMAIN-SUFFIX,whatsapp.com,Auto Select
- GEOIP,IR,DIRECT
- MATCH,Proxy Select
ntp:
  enable: true
  server: time.cloudflare.com
  port: 123
  interval: 30
